iris/app/urls.py
from django.urls import path

from iris.app.views import (
    CancelItemView,
    CommitFormView,
    CreateCommitForTaskView,
    CreateDelayForTaskView,
    CreateItemView,
    CreateSuspensionForTaskView,
    DelayEndView,
    DelayFormView,
    GeneralTaskListView,
    IndexView,
    IrisLoginView,
    IrisLogoutView,
    ItemFormView,
    ItemListView,
    RestoreItemView,
    StationTaskListView,
    SuspensionFormView,
    SuspensionLiftView,
    TaskDetailView,
    TasksWithIssuesView,
)

app_name = "iris"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", IrisLoginView.as_view(), name="login"),
    path("logout/", IrisLogoutView.as_view(), name="logout"),
    path("station/<int:station>", StationTaskListView.as_view(), name="station"),
    path(
        "station/<int:station>/<str:status>",
        StationTaskListView.as_view(),
        name="station",
    ),
    path("issues/", TasksWithIssuesView.as_view(), name="issues"),
    path("issues/<str:status>", TasksWithIssuesView.as_view(), name="issues"),
    path("tasks/", GeneralTaskListView.as_view(), name="task_list"),
    path("tasks/<str:status>", GeneralTaskListView.as_view(), name="task_list"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path(
        "task/<int:pk>/commit/add/",
        CreateCommitForTaskView.as_view(),
        name="task_add_commit",
    ),
    path(
        "task/<int:pk>/delay/add/",
        CreateDelayForTaskView.as_view(),
        name="task_add_delay",
    ),
    path(
        "task/<int:pk>/suspension/add/",
        CreateSuspensionForTaskView.as_view(),
        name="task_add_suspension",
    ),
    path(
        "commit/<int:pk>/change/",
        CommitFormView.as_view(),
        name="commit_change",
    ),
    path("delay/<int:pk>/change/", DelayFormView.as_view(), name="delay_change"),
    path("delay/<int:pk>/end/", DelayEndView.as_view(), name="delay_end"),
    path(
        "suspension/<int:pk>/change/",
        SuspensionFormView.as_view(),
        name="suspension_change",
    ),
    path(
        "suspension/<int:pk>/lift/",
        SuspensionLiftView.as_view(),
        name="suspension_lift",
    ),
    path("items/", ItemListView.as_view(), name="item_list"),
    path("items/<str:status>", ItemListView.as_view(), name="item_list"),
    path("item/<int:pk>/change/", ItemFormView.as_view(), name="item_change"),
    path("item/<int:pk>/cancel/", CancelItemView.as_view(), name="item_cancel"),
    path("item/<int:pk>/restore/", RestoreItemView.as_view(), name="item_restore"),
    path("item/add/", CreateItemView.as_view(), name="item_add"),
]

iris/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.views.static import serve

admin.site.index_title = _("Iris Admin")
admin.site.site_header = _("Iris Admin")
admin.site.site_title = _("Admin")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("iris.app.urls")),
]

if settings.DEBUG == True:
    urlpatterns.insert(
        0,
        re_path(
            "media/(?P<path>.*)",
            serve,
            {"document_root": settings.MEDIA_ROOT},
        ),
    )

iris/app/templates/iris/task_cards/buttons/create_commit.html
{% load i18n %}

{% if perms.iris.add_commit and user.worker %}
<a class="btn btn-success" href="{% url 'iris:task_add_commit' task.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Commit" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/create_delay.html
{% load i18n %}

{% if perms.iris.add_delay and user.worker %}
<a class="btn btn-warning" href="{% url 'iris:task_add_delay' task.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Delay" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/create_suspension.html
{% load i18n %}

{% if perms.iris.add_suspension and user.worker %}
<a class="btn btn-danger" href="{% url 'iris:task_add_suspension' task.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Suspend" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/edit_commit.html
{% load i18n %}

{% if perms.iris.change_commit %}
<a class="btn btn-primary" href="{% url 'iris:commit_change' task.commit.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Edit commit notes" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/edit_delay.html
{% load i18n %}

{% if perms.iris.change_delay %}
<a class="btn btn-primary" href="{% url 'iris:delay_change' task.delayed_by.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Edit delay" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/edit_suspension.html
{% load i18n %}

{% if perms.iris.change_suspension %}
<a class="btn btn-primary" href="{% url 'iris:suspension_change' task.suspended_by.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Edit suspension notes" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/end_delay.html
{% load i18n %}

{% if perms.iris.change_delay %}
<a class="btn btn-danger" href="{% url 'iris:delay_end' task.delayed_by.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "End delay" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/goto_item.html
{% load i18n %}

{% if perms.iris.change_item %}
<a class="btn btn-primary" href="{% url 'iris:item_change' task.item.pk %}">{% translate "Item details" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/goto_task.html
{% load i18n %}

{% if perms.iris.view_task %}
<a class="btn btn-primary" href="{% url 'iris:task_detail' task.pk %}">{% translate "Details" %}</a>
{% endif %}

iris/app/templates/iris/task_cards/buttons/lift_suspension.html
{% load i18n %}

{% if perms.iris.change_suspension %}
<a class="btn btn-danger" href="{% url 'iris:suspension_lift' task.suspended_by.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Lift suspension" %}</a>
{% endif %}