iris/app/urls.py
from django.urls import path

from iris.app.views import (
    CancelItemView,
    CommitFormView,
    CreateCommitForTaskView,
    CreateDelayForTaskView,
    CreateItemView,
    CreateSuspensionForTaskView,
    DelayEndView,
    DelayFormView,
    GeneralTaskListView,
    IndexView,
    IrisLoginView,
    IrisLogoutView,
    ItemFormView,
    ItemListView,
    RestoreItemView,
    StationTaskListView,
    SuspensionFormView,
    SuspensionLiftView,
    TaskDetailView,
    TasksWithIssuesView,
)

app_name = "iris"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", IrisLoginView.as_view(), name="login"),
    path("logout/", IrisLogoutView.as_view(), name="logout"),
    path("station/<int:station>", StationTaskListView.as_view(), name="station"),
    path(
        "station/<int:station>/<str:status>",
        StationTaskListView.as_view(),
        name="station",
    ),
    path("issues/", TasksWithIssuesView.as_view(), name="issues"),
    path("issues/<str:status>", TasksWithIssuesView.as_view(), name="issues"),
    path("tasks/", GeneralTaskListView.as_view(), name="task_list"),
    path("tasks/<str:status>", GeneralTaskListView.as_view(), name="task_list"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path(
        "task/<int:pk>/commit/add/",
        CreateCommitForTaskView.as_view(),
        name="task_add_commit",
    ),
    path(
        "task/<int:pk>/delay/add/",
        CreateDelayForTaskView.as_view(),
        name="task_add_delay",
    ),
    path(
        "task/<int:pk>/suspension/add/",
        CreateSuspensionForTaskView.as_view(),
        name="task_add_suspension",
    ),
    path(
        "commit/<int:pk>/change/",
        CommitFormView.as_view(),
        name="commit_change",
    ),
    path("delay/<int:pk>/change/", DelayFormView.as_view(), name="delay_change"),
    path("delay/<int:pk>/end/", DelayEndView.as_view(), name="delay_end"),
    path(
        "suspension/<int:pk>/change/",
        SuspensionFormView.as_view(),
        name="suspension_change",
    ),
    path(
        "suspension/<int:pk>/lift/",
        SuspensionLiftView.as_view(),
        name="suspension_lift",
    ),
    path("items/", ItemListView.as_view(), name="item_list"),
    path("items/<str:status>", ItemListView.as_view(), name="item_list"),
    path("item/<int:pk>/change/", ItemFormView.as_view(), name="item_change"),
    path("item/<int:pk>/cancel/", CancelItemView.as_view(), name="item_cancel"),
    path("item/<int:pk>/restore/", RestoreItemView.as_view(), name="item_restore"),
    path("item/add/", CreateItemView.as_view(), name="item_add"),
]

iris/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.views.static import serve

admin.site.index_title = _("Iris Admin")
admin.site.site_header = _("Iris Admin")
admin.site.site_title = _("Admin")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("iris.app.urls")),
]

if settings.DEBUG == True:
    urlpatterns.insert(
        0,
        re_path(
            "media/(?P<path>.*)",
            serve,
            {"document_root": settings.MEDIA_ROOT},
        ),
    )

iris/app/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, ValidationError
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from iris.app.managers import (
    DelayQuerySet,
    ItemQuerySet,
    SuspensionQuerySet,
    TaskQuerySet,
)

NOTES_PATH_LIMIT = 64


class NotCanceledError(Exception):
    pass


class AlreadyCanceledError(Exception):
    pass


class NotSuspendedError(Exception):
    pass


class AlreadyEndedError(Exception):
    pass


_notes_registry = set()


def get_note_types():
    return _notes_registry


def add_note_type(name, path):
    if len(path) > NOTES_PATH_LIMIT:
        raise RuntimeError(
            f"Notes registry path value must be under {NOTES_PATH_LIMIT} characters"
        )
    if (name, path) not in _notes_registry:
        _notes_registry.add((name, path))
    else:
        raise RuntimeError(f"Note types registry duplicate value for {name}, {path}")


class IrisStrMixin(models.Model):
    def __str__(self):
        return f"{self.__class__.__name__} #{self.pk}"

    class Meta:
        abstract = True


class TimestampMixin(models.Model):
    created = models.DateTimeField(_("created"), auto_now_add=True)
    modified = models.DateTimeField(_("modified"), auto_now=True)

    class Meta:
        abstract = True


class CancelableMixin(models.Model):
    cancel_time = models.DateTimeField(_("cancelation time"), editable=False, null=True)
    cancel_reason = models.CharField(
        _("cancelation reason"), max_length=256, editable=False
    )

    class Meta:
        abstract = True

    def cancel(self, reason, datetime_=None):
        if datetime_ is None:
            datetime_ = now()
        if self.canceled:
            raise AlreadyCanceledError(
                _("'{obj_name}' is already canceled.").format(
                    obj_name=str(self),
                ),
            )
        self.cancel_time = datetime_
        self.cancel_reason = reason
        self.save()

    def restore(self):
        if not self.canceled:
            raise NotCanceledError(
                _("'{obj_name}' is not canceled.").format(
                    obj_name=str(self),
                ),
            )
        self.cancel_time = None
        self.cancel_reason = ""
        self.save()

    @property
    def canceled(self):
        return self.cancel_reason != "" or self.cancel_time is not None

    def clean(self):
        super().clean()
        if (self.cancel_reason != "" and self.cancel_time is None) or (
            self.cancel_reason == "" and self.cancel_time is not None
        ):
            raise ValidationError(
                _("Cancelation reason and time must be specified at the same time.")
            )


class NotesMixin(models.Model):
    notes = models.TextField(_("notes"), blank=True)

    class Meta:
        abstract = True


class Item(IrisStrMixin, TimestampMixin, CancelableMixin, NotesMixin, models.Model):
    process = models.ForeignKey(
        "Process",
        verbose_name=_("process"),
        on_delete=models.RESTRICT,
        related_name="items",
    )
    description = models.CharField(_("description"), max_length=128, blank=True)
    quantity = models.IntegerField(
        _("quantity"), default=1, validators=[MinValueValidator(1)]
    )
    has_priority = models.BooleanField(_("has priority"), default=False)

    objects = ItemQuerySet.as_manager()

    class Meta:
        verbose_name = _("item")
        verbose_name_plural = _("items")

    @property
    def completed(self):
        all_tasks = Task.objects.filter(item=self)
        return all([task.completed for task in all_tasks])

    def spawn_tasks(self):
        for transition in self.process.step_transitions.all():
            if transition.required_steps.count() == 0:
                new_task = Task(item=self, step_transition=transition)
                new_task.save()


add_note_type("Item", "iris.app.Item")


class Process(IrisStrMixin, models.Model):
    name = models.CharField(_("name"), max_length=64)

    class Meta:
        verbose_name = _("process")
        verbose_name_plural = _("processes")


class Step(IrisStrMixin, models.Model):
    name = models.CharField(_("name"), max_length=64)
    instructions = models.TextField(_("instructions"), blank=True)
    stations = models.ManyToManyField(
        "Station", verbose_name=_("stations"), related_name="steps", blank=True
    )

    class Meta:
        verbose_name = _("step")
        verbose_name_plural = _("steps")


class Task(IrisStrMixin, TimestampMixin, models.Model):
    step_transition = models.ForeignKey(
        "StepTransition",
        verbose_name=_("step transition"),
        on_delete=models.RESTRICT,
        related_name="tasks",
    )
    item = models.ForeignKey(
        "Item", verbose_name=_("item"), on_delete=models.RESTRICT, related_name="tasks"
    )

    objects = TaskQuerySet.as_manager()

    class Meta:
        verbose_name = _("task")
        verbose_name_plural = _("tasks")

    @property
    def canceled(self):
        return self.item.canceled

    @property
    def completed(self):
        return hasattr(self, "commit")

    @property
    def delayed(self):
        return any(
            [(delay.created + delay.duration) > now() for delay in self.delays.all()]
        )

    @property
    def delayed_by(self):
        for delay in self.delays.all():
            if (delay.created + delay.duration) > now():
                return delay

    @property
    def suspended(self):
        return any([not suspension.lifted for suspension in self.suspensions.all()])

    @property
    def suspended_by(self):
        for suspension in self.suspensions.all():
            if not suspension.lifted:
                return suspension


class StepTransition(IrisStrMixin, models.Model):
    process = models.ForeignKey(
        "Process",
        verbose_name=_("process"),
        on_delete=models.CASCADE,
        related_name="step_transitions",
    )
    required_steps = models.ManyToManyField(
        "self",
        verbose_name=_("required steps"),
        through="StepTransitionRequiredSteps",
        symmetrical=False,
        related_name="required_by",
    )
    creates = models.ForeignKey(
        "Step",
        verbose_name=_("creates"),
        on_delete=models.RESTRICT,
        related_name="created_by",
    )

    class Meta:
        verbose_name = _("step transition")
        verbose_name_plural = _("step transitions")


class StepTransitionRequiredSteps(IrisStrMixin, models.Model):
    step_transition = models.ForeignKey(
        "StepTransition", on_delete=models.CASCADE, related_name="step_transition"
    )
    requirement = models.ForeignKey(
        "StepTransition", on_delete=models.CASCADE, related_name="requirement"
    )


class Worker(IrisStrMixin, models.Model):
    user = models.OneToOneField(
        get_user_model(),
        verbose_name=_("user"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _("worker")
        verbose_name_plural = _("workers")


class Commit(IrisStrMixin, TimestampMixin, NotesMixin, models.Model):
    task = models.OneToOneField(
        "Task", verbose_name=_("task"), on_delete=models.CASCADE
    )
    worker = models.ForeignKey(
        "Worker",
        verbose_name=_("worker"),
        on_delete=models.RESTRICT,
        related_name="commits",
    )

    class Meta:
        verbose_name = _("commit")
        verbose_name_plural = _("commits")

    def spawn_and_consolidate_tasks(self):
        for required_by in self.task.step_transition.required_by.all():
            required_steps = required_by.required_steps.all()
            required_tasks = Task.objects.filter(
                item=self.task.item, step_transition__in=required_steps
            )
            if len(required_steps) == len(required_tasks) and all(
                [task.completed for task in required_tasks]
            ):
                new_task = Task(item=self.task.item, step_transition=required_by)
                new_task.save()


add_note_type("Commit", "iris.app.Commit")


class Station(IrisStrMixin, models.Model):
    name = models.CharField(_("name"), max_length=64)

    class Meta:
        verbose_name = _("station")
        verbose_name_plural = _("stations")


class NoteTemplate(IrisStrMixin, models.Model):
    path = models.CharField(_("path"), max_length=NOTES_PATH_LIMIT)
    template = models.CharField(_("template"), max_length=256)

    class Meta:
        verbose_name = _("note template")
        verbose_name_plural = _("note templates")


class Delay(IrisStrMixin, TimestampMixin, NotesMixin, models.Model):
    task = models.ForeignKey(
        "Task", verbose_name=_("task"), on_delete=models.CASCADE, related_name="delays"
    )
    worker = models.ForeignKey(
        "Worker",
        verbose_name=_("worker"),
        on_delete=models.RESTRICT,
        related_name="delays",
    )
    duration = models.DurationField(_("duration"))

    objects = DelayQuerySet.as_manager()

    class Meta:
        verbose_name = _("delay")
        verbose_name_plural = _("delays")

    @property
    def in_effect(self):
        return self.created + self.duration > now()

    @property
    def ends(self):
        return self.created + self.duration

    def end(self):
        if not self.in_effect:
            raise AlreadyEndedError(
                _("Delay '{delay_name}' has already ended.").format(
                    delay_name=str(self),
                )
            )
        self.duration = now() - self.created
        self.save()


add_note_type("Delay", "iris.app.Delay")


class Suspension(IrisStrMixin, TimestampMixin, NotesMixin, models.Model):
    task = models.ForeignKey(
        "Task",
        verbose_name=_("task"),
        on_delete=models.CASCADE,
        related_name="suspensions",

iris/app/admin/forms.py
from django import forms
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from iris.app.models import Worker


class BrowserDateInput(forms.DateTimeInput):
    input_type = "datetime-local"


class CancelItemsViewForm(forms.Form):
    reason = forms.CharField(label=_("Reason"))
    datetime = forms.DateTimeField(
        label=_("Date/Time"), widget=BrowserDateInput(), initial=now
    )


class WorkerModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.user.username


class AddCommitTasksViewForm(forms.Form):
    worker = WorkerModelChoiceField(queryset=Worker.objects.all())


class AddDelayTasksViewForm(forms.Form):
    worker = WorkerModelChoiceField(queryset=Worker.objects.all())
    duration = forms.DurationField()


class AddSuspendTasksViewForm(forms.Form):
    worker = WorkerModelChoiceField(queryset=Worker.objects.all())

iris/app/forms.py
from datetime import timedelta

from django import forms
from django.core.validators import ValidationError
from django.utils.timezone import now
from django.utils.translation import gettext as _

from iris.app.models import Delay, Item


class DelayModelForm(forms.ModelForm):
    days = forms.IntegerField(min_value=0, required=True)
    hours = forms.IntegerField(min_value=0, required=True)
    minutes = forms.IntegerField(min_value=0, required=True)

    class Meta:
        model = Delay
        fields = ["notes"]

    def __init__(self, *args, **kwargs):
        instance = kwargs["instance"]
        if instance is not None:
            remainder = int(instance.duration.total_seconds())
            days = kwargs["initial"]["days"] = remainder // 86400
            remainder -= days * 86400
            hours = kwargs["initial"]["hours"] = remainder // 3600
            remainder -= hours * 3600
            minutes = kwargs["initial"]["minutes"] = remainder // 60
            remainder -= minutes * 60
            kwargs["initial"].update(
                {
                    "days": days,
                    "hours": hours,
                    "minutes": minutes,
                }
            )
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        try:
            duration = timedelta(
                days=cleaned_data["days"],
                hours=cleaned_data["hours"],
                minutes=cleaned_data["minutes"],
            )
        except KeyError:
            raise ValidationError(_("Delays must have a duration."), code="invalid")
        else:
            if duration == timedelta():
                raise ValidationError(_("Delays must have a duration."), code="invalid")

    def save(self):
        self.instance.duration = timedelta(
            days=self.cleaned_data["days"],
            hours=self.cleaned_data["hours"],
            minutes=self.cleaned_data["minutes"],
        )
        return super().save()


class CreateItemModelForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["process", "description", "notes", "quantity"]

    def save(self):
        instance = super().save()
        instance.spawn_tasks()
        return instance


class CancelItemForm(forms.ModelForm):
    reason = forms.CharField(required=True)
    time = forms.DateTimeField(required=True, initial=now)

    class Meta:
        model = Item
        fields = []

    def save(self):
        self.instance.cancel(
            self.cleaned_data["reason"],
            self.cleaned_data["time"],
        )
        return super().save()

iris/app/templates/iris/commit_form.html
{% extends 'iris/base.html' %}

{% load i18n %}

{% block iris_title %}{% block iris_header %}{% blocktranslate %}Editing commit {{ object.pk }}{% endblocktranslate %}{% endblock %}{% endblock %}

{% block content %}
<div class="container-sm mt-4 p-4">
	<form method="post">
		{% csrf_token %}
		<input type="hidden" id="next_url" value="{{ next_url }}">
		{% if form.non_field_errors %}
		<ul class="mb-3 row text-danger">
			{% for error in form.non_field_errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		<div class="mb-3 row">
			<div class="col">
				<label for="id_notes" class="form-label">{% translate "Notes" %}</label>
				<textarea id="id_notes" name="notes" class="form-control" rows="10">{{ object.notes }}</textarea>
				{% if form.notes.errors %}
				<ul class="text-danger">
					{% for error in form.notes.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div>
			<button type="submit" class="btn btn-primary w-100">{% translate "Save changes" %}</button>
		</div>
	</form>
</div>
{% endblock %}

iris/app/templates/iris/delay_create_for_job.html
{% extends 'iris/base.html' %}

{% load i18n %}

{% block iris_title %}{% blocktranslate with job_id=job.pk %}Create delay for job {{ job_id }}{% endblocktranslate %}{% endblock %}
{% block iris_header %}{% blocktranslate with job_name=job %}Create delay for {{ job_name }}{% endblocktranslate %}{% endblock %}

{% block content %}
<div class="container-sm mt-4 p-4">
	<form method="post">
		{% csrf_token %}
		{% if form.non_field_errors %}
		<ul class="mb-3 row text-danger">
			{% for error in form.non_field_errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		<div class="mb-3 row">
			<div class="col">
				<label class="form-label" for="id_days">{% translate "Days" %}</label>
				<input class="form-control" type="number" name="days" id="id_days" value="0">
				{% if form.days.errors %}
				<ul class="text-danger">
					{% for error in form.days.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
			<div class="col">
				<label class="form-label" for="id_hours">{% translate "Hours" %}</label>
				<input class="form-control" type="number" name="hours" id="id_hours" value="0">
				{% if form.hours.errors %}
				<ul class="text-danger">
					{% for error in form.hours.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
			<div class="col">
				<label class="form-label" for="id_minutes">{% translate "Minutes" %}</label>
				<input class="form-control" type="number" name="minutes" id="id_minutes" value="0">
				{% if form.minutes.errors %}
				<ul class="text-danger">
					{% for error in form.minutes.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div class="mb-3 row">
			<div class="col">
				<label for="id_notes" class="form-label">{% translate "Notes" %}</label>
				<textarea id="id_notes" name="notes" class="form-control" rows="10"></textarea>
				{% if form.notes.errors %}
				<ul class="text-danger">
					{% for error in form.notes.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div>
			<button type="submit" class="btn btn-primary w-100">{% translate "Delay" %}</button>
		</div>
	</form>
</div>
{% endblock %}

iris/app/templates/iris/delay_form.html
{% extends 'iris/base.html' %}

{% load i18n %}

{% block iris_title %}{% block iris_header %}{% blocktranslate %}Editing delay {{ object.pk }}{% endblocktranslate %}{% endblock %}{% endblock %}

{% block content %}
<div class="container-sm mt-4 p-4">
	<form method="post">
		{% csrf_token %}
		<input type="hidden" id="next_url" value="{{ next_url }}">
		{% if form.non_field_errors %}
		<ul class="mb-3 row text-danger">
			{% for error in form.non_field_errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		<div class="mb-3 row">
			<div class="col">
				<label class="form-label" for="id_days">{% translate "Days" %}</label>
				<input class="form-control" type="number" name="days" id="id_days" value="{{ form.days.initial }}">
				{% if form.days.errors %}
				<ul class="text-danger">
					{% for error in form.days.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
			<div class="col">
				<label class="form-label" for="id_hours">{% translate "Hours" %}</label>
				<input class="form-control" type="number" name="hours" id="id_hours" value="{{ form.hours.initial }}">
				{% if form.hours.errors %}
				<ul class="text-danger">
					{% for error in form.hours.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
			<div class="col">
				<label class="form-label" for="id_minutes">{% translate "Minutes" %}</label>
				<input class="form-control" type="number" name="minutes" id="id_minutes" value="{{ form.minutes.initial }}">
				{% if form.minutes.errors %}
				<ul class="text-danger">
					{% for error in form.minutes.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div class="mb-3 row">
			<div class="col">
				<label for="id_notes" class="form-label">{% translate "Notes" %}</label>
				<textarea id="id_notes" name="notes" class="form-control" rows="10">{{ object.notes }}</textarea>
				{% if form.notes.errors %}
				<ul class="text-danger">
					{% for error in form.notes.errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		</div>
		<div>
			<button type="submit" class="btn btn-primary w-100">{% translate "Save changes" %}</button>
		</div>
	</form>
</div>
{% endblock %}

iris/app/templates/iris/job_card_inline.html
{% load i18n %}

<div class="container mt-4">
	{% if job.completed %}
	<div class="card border-success">
		<div class="card-header text-success">{% translate "This job has been completed." %}</div>
	{% elif job.delayed %}
	<div class="card border-warning">
		<div class="card-header text-dark text-warning">{% translate "This job is delayed." %}</div>
	{% elif job.suspended %}
	<div class="card border-danger">
		<div class="card-header text-danger">{% translate "This job is suspended." %}</div>
	{% else %}
	<div class="card">
	{% endif %}
		<div class="card-header">
			<h5 class="card-title">{{ job.task.name }}</h5>
			{% if job.work.quantity != 1 %}<h6 class="card-subtitle mb-2 text-muted">{% blocktranslate with quantity=job.work.quantity %}{{ quantity }} times{% endblocktranslate %}</h6>{% endif %}
		</div>
		<ul class="list-group list-group-flush">
			<li class="list-group-item">{{ job.work }}</li>
			{% if job.completed and job.commit.notes %}
			<li class="list-group-item">
				<p>{% translate "Commit notes" %}</p>
				<p>{{ job.commit.notes|linebreaks }}</p>
			</li>
			{% endif %}
		</ul>
		<div class="card-footer">
			<a class="btn btn-primary" href="{% url 'iris:job_detail' job.pk %}">{% translate "Job details" %}</a>
			{% if job.completed %}
			<a class="btn btn-primary" href="{% url 'iris:commit_change' job.commit.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Edit commit notes" %}</a>
			{% endif %}
		</div>
	</div>
</div>

iris/app/templates/iris/job_card_station_completed.html
{% load i18n %}

<div class="container mt-4">
	<div class="card">
		<div class="card-header">
			<h5 class="card-title">{{ job.task.name }}</h5>
			{% if job.work.quantity != 1 %}<h6 class="card-subtitle mb-2 text-muted">{% blocktranslate with quantity=job.work.quantity %}{{ quantity }} times{% endblocktranslate %}</h6>{% endif %}
			<p class="card-text">{{ job.work }}</p>
		</div>
		{% if job.commit.notes %}
		<ul class="list-group list-group-flush">
			<li class="list-group-item">
				<p>{% translate "Commit notes" %}</p>
				<p>{{ job.commit.notes|linebreaks }}</p>
			</li>
		</ul>
		{% endif %}
		<div class="card-footer">
			<a class="btn btn-primary" href="{% url 'iris:job_detail' job.pk %}">{% translate "Job details" %}</a>
			<a class="btn btn-primary" href="{% url 'iris:commit_change' job.commit.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Edit commit notes" %}</a>
		</div>
	</div>
</div>

iris/app/templates/iris/job_card_station_delayed.html
{% load i18n %}

<div class="container mt-4">
	<div class="card">
		<div class="card-header">
			<h5 class="card-title">{{ job.task.name }}</h5>
			{% if job.work.quantity != 1 %}<h6 class="card-subtitle mb-2 text-muted">{% blocktranslate with quantity=job.work.quantity %}{{ quantity }} times{% endblocktranslate %}</h6>{% endif %}
			<p class="card-text">{{ job.work }}</p>
		</div>
		{% if job.delayed_by.notes %}
		<ul class="list-group list-group-flush">
			<li class="list-group-item">
				<p>{% translate "Delay notes" %}</p>
				<p>{{ job.delayed_by.notes|linebreaks }}</p>
			</li>
		</ul>
		{% endif %}
		<div class="card-footer">
			<a class="btn btn-primary" href="{% url 'iris:job_detail' job.pk %}">{% translate "Job details" %}</a>
			<a class="btn btn-primary" href="{% url 'iris:delay_change' job.delayed_by.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Edit delay" %}</a>
			<a class="btn btn-danger" href="{% url 'iris:delay_end' job.delayed_by.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "End delay" %}</a>
		</div>
	</div>
</div>

iris/app/templates/iris/job_card_station_suspended.html
{% load i18n %}

<div class="container mt-4">
	<div class="card">
		<div class="card-header">
			<h5 class="card-title">{{ job.task.name }}</h5>
			{% if job.work.quantity != 1 %}<h6 class="card-subtitle mb-2 text-muted">{% blocktranslate with quantity=job.work.quantity %}{{ quantity }} times{% endblocktranslate %}</h6>{% endif %}
			<p class="card-text">{{ job.work }}</p>
		</div>
		{% if job.suspended_by.notes %}
		<ul class="list-group list-group-flush">
			<li class="list-group-item">
				<p>{% translate "Suspension notes" %}</p>
				<p>{{ job.suspended_by.notes|linebreaks }}</p>
			</li>
		</ul>
		{% endif %}
		<div class="card-footer">
			<a class="btn btn-primary" href="{% url 'iris:job_detail' job.pk %}">{% translate "Job details" %}</a>
			<a class="btn btn-primary" href="{% url 'iris:suspension_change' job.suspended_by.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Edit suspension notes" %}</a>
			<a class="btn btn-danger" href="{% url 'iris:suspension_lift' job.suspended_by.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Lift suspension" %}</a>
		</div>
	</div>
</div>