iris/app/urls.py
from django.urls import path

from iris.app.views import (
    CancelItemView,
    CommitFormView,
    CreateCommitForTaskView,
    CreateDelayForTaskView,
    CreateItemView,
    CreateSuspensionForTaskView,
    DelayEndView,
    DelayFormView,
    GeneralTaskListView,
    IndexView,
    IrisLoginView,
    IrisLogoutView,
    ItemFormView,
    ItemListView,
    RestoreItemView,
    StationTaskListView,
    SuspensionFormView,
    SuspensionLiftView,
    TaskDetailView,
    TasksWithIssuesView,
)

app_name = "iris"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", IrisLoginView.as_view(), name="login"),
    path("logout/", IrisLogoutView.as_view(), name="logout"),
    path("station/<int:station>", StationTaskListView.as_view(), name="station"),
    path(
        "station/<int:station>/<str:status>",
        StationTaskListView.as_view(),
        name="station",
    ),
    path("issues/", TasksWithIssuesView.as_view(), name="issues"),
    path("issues/<str:status>", TasksWithIssuesView.as_view(), name="issues"),
    path("tasks/", GeneralTaskListView.as_view(), name="task_list"),
    path("tasks/<str:status>", GeneralTaskListView.as_view(), name="task_list"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path(
        "task/<int:pk>/commit/add/",
        CreateCommitForTaskView.as_view(),
        name="task_add_commit",
    ),
    path(
        "task/<int:pk>/delay/add/",
        CreateDelayForTaskView.as_view(),
        name="task_add_delay",
    ),
    path(
        "task/<int:pk>/suspension/add/",
        CreateSuspensionForTaskView.as_view(),
        name="task_add_suspension",
    ),
    path(
        "commit/<int:pk>/change/",
        CommitFormView.as_view(),
        name="commit_change",
    ),
    path("delay/<int:pk>/change/", DelayFormView.as_view(), name="delay_change"),
    path("delay/<int:pk>/end/", DelayEndView.as_view(), name="delay_end"),
    path(
        "suspension/<int:pk>/change/",
        SuspensionFormView.as_view(),
        name="suspension_change",
    ),
    path(
        "suspension/<int:pk>/lift/",
        SuspensionLiftView.as_view(),
        name="suspension_lift",
    ),
    path("items/", ItemListView.as_view(), name="item_list"),
    path("items/<str:status>", ItemListView.as_view(), name="item_list"),
    path("item/<int:pk>/change/", ItemFormView.as_view(), name="item_change"),
    path("item/<int:pk>/cancel/", CancelItemView.as_view(), name="item_cancel"),
    path("item/<int:pk>/restore/", RestoreItemView.as_view(), name="item_restore"),
    path("item/add/", CreateItemView.as_view(), name="item_add"),
]

iris/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.views.static import serve

admin.site.index_title = _("Iris Admin")
admin.site.site_header = _("Iris Admin")
admin.site.site_title = _("Admin")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("iris.app.urls")),
]

if settings.DEBUG == True:
    urlpatterns.insert(
        0,
        re_path(
            "media/(?P<path>.*)",
            serve,
            {"document_root": settings.MEDIA_ROOT},
        ),
    )

iris/app/admin/forms.py
from django import forms
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from iris.app.models import Worker


class BrowserDateInput(forms.DateTimeInput):
    input_type = "datetime-local"


class CancelItemsViewForm(forms.Form):
    reason = forms.CharField(label=_("Reason"))
    datetime = forms.DateTimeField(
        label=_("Date/Time"), widget=BrowserDateInput(), initial=now
    )


class WorkerModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.user.username


class AddCommitTasksViewForm(forms.Form):
    worker = WorkerModelChoiceField(queryset=Worker.objects.all())


class AddDelayTasksViewForm(forms.Form):
    worker = WorkerModelChoiceField(queryset=Worker.objects.all())
    duration = forms.DurationField()


class AddSuspendTasksViewForm(forms.Form):
    worker = WorkerModelChoiceField(queryset=Worker.objects.all())

iris/app/forms.py
from datetime import timedelta

from django import forms
from django.core.validators import ValidationError
from django.utils.timezone import now
from django.utils.translation import gettext as _

from iris.app.models import Delay, Item


class DelayModelForm(forms.ModelForm):
    days = forms.IntegerField(min_value=0, required=True)
    hours = forms.IntegerField(min_value=0, required=True)
    minutes = forms.IntegerField(min_value=0, required=True)

    class Meta:
        model = Delay
        fields = ["notes"]

    def __init__(self, *args, **kwargs):
        instance = kwargs["instance"]
        if instance is not None:
            remainder = int(instance.duration.total_seconds())
            days = kwargs["initial"]["days"] = remainder // 86400
            remainder -= days * 86400
            hours = kwargs["initial"]["hours"] = remainder // 3600
            remainder -= hours * 3600
            minutes = kwargs["initial"]["minutes"] = remainder // 60
            remainder -= minutes * 60
            kwargs["initial"].update(
                {
                    "days": days,
                    "hours": hours,
                    "minutes": minutes,
                }
            )
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        try:
            duration = timedelta(
                days=cleaned_data["days"],
                hours=cleaned_data["hours"],
                minutes=cleaned_data["minutes"],
            )
        except KeyError:
            raise ValidationError(_("Delays must have a duration."), code="invalid")
        else:
            if duration == timedelta():
                raise ValidationError(_("Delays must have a duration."), code="invalid")

    def save(self):
        self.instance.duration = timedelta(
            days=self.cleaned_data["days"],
            hours=self.cleaned_data["hours"],
            minutes=self.cleaned_data["minutes"],
        )
        return super().save()


class CreateItemModelForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["process", "description", "notes", "quantity"]

    def save(self):
        instance = super().save()
        instance.spawn_tasks()
        return instance


class CancelItemForm(forms.ModelForm):
    reason = forms.CharField(required=True)
    time = forms.DateTimeField(required=True, initial=now)

    class Meta:
        model = Item
        fields = []

    def save(self):
        self.instance.cancel(
            self.cleaned_data["reason"],
            self.cleaned_data["time"],
        )
        return super().save()

iris/app/admin/views.py
from django.contrib import admin, messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from iris.app.admin.forms import (
    AddCommitTasksViewForm,
    AddDelayTasksViewForm,
    AddSuspendTasksViewForm,
    CancelItemsViewForm,
)
from iris.app.models import AlreadyCanceledError, Commit, Delay, Item, Suspension, Task


class AdminContextMixin:
    def get_context_data(self, **kwargs):
        context = {
            **super().get_context_data(**kwargs),
            **admin.site.each_context(self.request),
        }
        if hasattr(self, "model"):
            context |= {
                "opts": self.model._meta,
            }
        return context


class CancelItemsView(AdminContextMixin, PermissionRequiredMixin, FormView):
    permission_required = "iris.change_item"
    template_name = "admin/iris/item/cancel_items.html"
    form_class = CancelItemsViewForm
    success_url = reverse_lazy("admin:iris_item_changelist")

    def get(self, request, *args, **kwargs):
        ids = self.request.GET["ids"]
        items = Item.objects.filter(pk__in=ids.split(","))
        for item in items:
            if item.canceled:
                messages.error(
                    self.request,
                    _("The item '{item_name}' is already canceled.").format(
                        item_name=str(item),
                    ),
                )
                return HttpResponseRedirect(reverse("admin:iris_item_changelist"))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ids = self.request.GET["ids"]
        items = Item.objects.filter(pk__in=ids.split(","))
        return {
            **super().get_context_data(**kwargs),
            "title": _("Cancel items"),
            "ids": ids,
            "items": items,
        }

    def form_valid(self, form):
        ids = self.request.GET["ids"]
        items = Item.objects.filter(pk__in=ids.split(","))
        reason = form.cleaned_data["reason"]
        datetime_ = form.cleaned_data["datetime"]
        try:
            with transaction.atomic():
                for item in items:
                    item.cancel(reason, datetime_)
        except AlreadyCanceledError as e:
            messages.error(self.request, str(e))
            return HttpResponseRedirect(self.request.path_info + f"?ids={ids}")
        else:
            messages.info(self.request, _("The items were canceled."))
            return super().form_valid(form)


class ConfirmationViewMixin(AdminContextMixin, PermissionRequiredMixin, TemplateView):
    template_name = "admin/iris/confirmation.html"
    confirmation_title = ""
    confirmation_text = ""

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            "title": self.confirmation_title,
            "confirmation_text": self.confirmation_text,
        }

    def confirmed(self, request):
        return bool(request.POST.get("confirm"))

    def confirm_again(self, request):
        ids = request.GET["ids"]
        messages.error(
            request, str(_("You have to check the confirmation box to continue."))
        )
        return HttpResponseRedirect(request.path_info + f"?ids={ids}")


class ItemSpawnTasksView(ConfirmationViewMixin):
    permission_required = "iris.add_task"
    confirmation_title = gettext_lazy("Confirm tasks creation")
    confirmation_text = gettext_lazy(
        "There are tasks already created for one or more of the selected items. "
        "Are you sure you want to proceed?"
    )

    @staticmethod
    def get_ids_and_items(request):
        ids = request.GET["ids"]
        items = Item.objects.filter(pk__in=ids.split(","))
        return ids, items

    def get(self, request, *args, **kwargs):
        _ids, items = self.get_ids_and_items(request)
        for item in items:
            if item.tasks.count() > 0:
                return super().get(request, *args, **kwargs)
        return self.apply(request)

    def get_context_data(self, **kwargs):
        ids, items = self.get_ids_and_items(self.request)
        return {
            **super().get_context_data(**kwargs),
            "ids": ids,
            "objects": items,
        }

    def post(self, request):
        if not self.confirmed(request):
            return self.confirm_again(request)
        return self.apply(request)

    def apply(self, request):
        _ids, items = self.get_ids_and_items(request)
        with transaction.atomic():
            for item in items:
                item.spawn_tasks()
        messages.info(request, _("Tasks spawned."))
        return HttpResponseRedirect(reverse("admin:iris_item_changelist"))


class CommitSpawnAndConsolidateTasksView(ConfirmationViewMixin):
    permission_required = "iris.add_task"
    confirmation_title = gettext_lazy("Confirm tasks creation")
    confirmation_text = gettext_lazy(
        "There are tasks already derived from one or more of the selected commits. "
        "Are you sure you want to proceed?"
    )

    @staticmethod
    def get_ids_and_commits(request):
        ids = request.GET["ids"]
        commits = Commit.objects.filter(pk__in=ids.split(","))
        return ids, commits

    def get(self, request, *args, **kwargs):
        _ids, commits = self.get_ids_and_commits(request)
        for commit in commits:
            potential_transitions = commit.task.step_transition.required_by.all()
            potential_tasks = Task.objects.filter(
                item=commit.task.item, step_transition__in=potential_transitions
            )
            if potential_tasks.count() > 0:
                return super().get(request, *args, **kwargs)
        return self.apply(request)

    def get_context_data(self, **kwargs):
        ids, commits = self.get_ids_and_commits(self.request)
        return {
            **super().get_context_data(**kwargs),
            "ids": ids,
            "objects": commits,
        }

    def post(self, request):
        if not self.confirmed(request):
            return self.confirm_again(request)
        return self.apply(request)

    def apply(self, request):
        _ids, commits = self.get_ids_and_commits(request)
        with transaction.atomic():
            for commit in commits:
                commit.spawn_and_consolidate_tasks()
        messages.info(request, _("Tasks spawned."))
        return HttpResponseRedirect(reverse("admin:iris_commit_changelist"))


class AddActionsTaskViewMixin(AdminContextMixin, FormView):
    success_url = reverse_lazy("admin:iris_task_changelist")
    action_title = ""
    action_attr = ""
    action_verb = ""
    action_conflicts = []

    def get_context_data(self, **kwargs):
        ids = self.request.GET["ids"]
        tasks = Task.objects.filter(pk__in=ids.split(","))
        return {
            **super().get_context_data(**kwargs),
            "title": self.action_title,
            "ids": ids,
            "tasks": tasks,
        }

    def log_action_applied_message(self, task):
        messages.error(
            self.request,
            _("The task '{task_name}' is already {verb}.").format(
                task_name=str(task),
                verb=self.action_verb,
            ),
        )

    def log_action_conflicted_message(self, task, verb):
        messages.error(
            self.request,
            _("The task '{task_name}' is {verb}.").format(
                task_name=str(task),
                verb=verb,
            ),
        )

    def check_and_log(self, task):
        if getattr(task, self.action_attr):
            self.log_action_applied_message(task)
            return True
        for attr, verb in self.action_conflicts:
            if getattr(task, attr):
                self.log_action_conflicted_message(task, verb)
                return True
        return False

    def get_ids_and_tasks(self, request):
        ids = request.GET["ids"]
        return ids, Task.objects.filter(pk__in=ids.split(","))

    def get(self, request, *args, **kwargs):
        _ids, tasks = self.get_ids_and_tasks(request)
        for task in tasks:
            if self.check_and_log(task):
                return HttpResponseRedirect(reverse("admin:iris_task_changelist"))
        return super().get(request, *args, **kwargs)


class CommitTasksView(PermissionRequiredMixin, AddActionsTaskViewMixin):
    permission_required = "iris.add_commit"
    template_name = "admin/iris/task/commit_tasks.html"
    form_class = AddCommitTasksViewForm
    action_title = gettext_lazy("Commit tasks")
    action_attr = "completed"
    action_verb = gettext_lazy("completed")
    action_conflicts = [
        ("delayed", gettext_lazy("delayed")),
        ("suspended", gettext_lazy("suspended")),
    ]

    def form_valid(self, form):
        ids, tasks = self.get_ids_and_tasks(self.request)
        worker = form.cleaned_data["worker"]
        with transaction.atomic():
            for task in tasks:
                if self.check_and_log(task):
                    return HttpResponseRedirect(self.request.path_info + f"?ids={ids}")
            for task in tasks:
                Commit(task=task, worker=worker).save()
        messages.info(self.request, _("The tasks were commited."))
        return super().form_valid(form)


class DelayTasksView(PermissionRequiredMixin, AddActionsTaskViewMixin):
    permission_required = "iris.add_delay"
    template_name = "admin/iris/task/delay_tasks.html"
    form_class = AddDelayTasksViewForm
    action_title = gettext_lazy("Delay tasks")
    action_attr = "delayed"
    action_verb = gettext_lazy("delayed")
    action_conflicts = [

iris/app/templates/iris/screens/issues.html
{% extends 'iris/base.html' %}

{% load i18n %}

{% block iris_title %}{% block iris_header %}{% translate 'Current issues' %}{% endblock %}{% endblock %}

{% block content %}
<div class="container mt-4">
	<div class="btn-group">
		<a href="{% url "iris:issues" %}" class="btn btn-primary{% if status == "with_issues" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Both" %}</a>
		<a href="{% url "iris:issues" status="delayed" %}" class="btn btn-primary{% if status == "delayed" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Delays" %}</a>
		<a href="{% url "iris:issues" status="suspended" %}" class="btn btn-primary{% if status == "suspended" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Suspensions" %}</a>
	</div>
	<ul>
		{% for task in object_list %}
		{% include "iris/task_cards/issues.html" %}
		{% endfor %}
	</ul>
</div>
{% endblock %}

iris/app/templates/iris/screens/items.html
{% extends 'iris/base.html' %}

{% load i18n %}
{% load iris_tags %}

{% block iris_title %}{% block iris_header %}{% translate "All items" %}{% endblock %}{% endblock %}

{% block content %}
<div class="container mt-4">
	<div class="container-flex">
		<div class="btn-group">
			<a href="{% url "iris:item_list" %}" class="btn btn-primary{% if status == "pending" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Pending" %}</a>
			<a href="{% url "iris:item_list" status="completed" %}" class="btn btn-primary{% if status == "completed" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Completed" %}</a>
			<a href="{% url "iris:item_list" status="canceled" %}" class="btn btn-primary{% if status == "canceled" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Canceled" %}</a>
		</div>
		{% if perms.iris.add_item %}
		<div class="btn-group">
			<a href="{% url "iris:item_add" %}?next={{ request.get_full_path|urlencode }}" class="btn btn-success">{% translate "Create new item" %}</a>
		</div>
		{% endif %}
	</div>
	<ul>
		{% for item in object_list %}
		<div class="container mt-4">
			{% if item.completed %}
			<div class="card border-success">
			{% elif item.canceled %}
			<div class="card border-danger">
			{% else %}
			<div class="card">
			{% endif %}
				{% if item.completed %}
				<div class="card-header text-success">{% translate "This item has been completed." %}</div>
				{% elif item.canceled %}
				<div class="card-header text-danger">{% translate "This item has been canceled." %}</div>
				{% endif %}
				<div class="card-header">
					<h5 class="card-title">{% make_item_title item %}</h5>
					{% if item.quantity != 1 %}<h6 class="card-subtitle mb-2 text-muted">{% blocktranslate with quantity=item.quantity %}{{ quantity }} times{% endblocktranslate %}</h6>{% endif %}
				</div>
				<ul class="list-group list-group-flush">
				<li class="list-group-item">
					{% if perms.iris.change_item %}
						<a class="btn btn-primary" href="{% url 'iris:item_change' item.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Edit item details" %}</a>
						{% if not item.canceled %}
							<a class="btn btn-danger" href="{% url 'iris:item_cancel' item.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Cancel item" %}</a>
						{% else %}
							<a class="btn btn-primary" href="{% url 'iris:item_restore' item.pk %}?next={{ request.get_full_path|urlencode }}">{% translate "Restore item" %}</a>
						{% endif %}
					{% endif %}
				</li>
				{% if item.notes %}
				<li class="list-group-item">
					<p>{% translate "Item notes" %}</p>
					<p>{{ item.notes|linebreaks }}</p>
				</li>
				{% endif %}
				<li class="list-group-item">
					<div class="card-body">{% translate "Task list" %}</div>
					{% for task in item.tasks.all %}
						{% include "iris/task_cards/inline.html" %}
					{% endfor %}
				</li>
				</ul>
			</div>
		</div>
		{% endfor %}
	</ul>
</div>
{% endblock %}

iris/app/templates/iris/screens/station.html
{% extends 'iris/base.html' %}

{% load i18n %}

{% block iris_title %}{% block iris_header %}{% blocktranslate with station_name=object.name %}Items for station {{ station_name }}{% endblocktranslate %}{% endblock %}{% endblock %}

{% block content %}
<div class="container mt-4">
	<div class="btn-group">
		<a href="{% url "iris:station" station=station.pk %}" class="btn btn-primary{% if status == "pending" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Pending" %}</a>
		<a href="{% url "iris:station" station=station.pk status="delayed" %}" class="btn btn-primary{% if status == "delayed" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Delayed" %}</a>
		<a href="{% url "iris:station" station=station.pk status="suspended" %}" class="btn btn-primary{% if status == "suspended" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Suspended" %}</a>
	</div>
	<ul>
		{% if status == "pending" %}
		{% for task in object_list %}{% include "iris/task_cards/station_pending.html" %}{% endfor %}
		{% elif status == "delayed" %}
		{% for task in object_list %}{% include "iris/task_cards/station_delayed.html" %}{% endfor %}
		{% elif status == "suspended" %}
		{% for task in object_list %}{% include "iris/task_cards/station_suspended.html" %}{% endfor %}
		{% endif %}
	</ul>
</div>
{% endblock %}

iris/app/templates/iris/screens/tasks.html
{% extends 'iris/base.html' %}

{% load i18n %}

{% block iris_title %}{% block iris_header %}{% translate "All tasks" %}{% endblock %}{% endblock %}

{% block content %}
<div class="container mt-4">
	<div class="btn-group">
		<a href="{% url "iris:task_list" %}" class="btn btn-primary{% if status == "pending" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Pending" %}</a>
		<a href="{% url "iris:task_list" status="delayed" %}" class="btn btn-primary{% if status == "delayed" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Delayed" %}</a>
		<a href="{% url "iris:task_list" status="suspended" %}" class="btn btn-primary{% if status == "suspended" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Suspended" %}</a>
		<a href="{% url "iris:task_list" status="completed" %}" class="btn btn-primary{% if status == "completed" %} active" aria-current="page"{% else %}"{% endif %}>{% translate "Completed" %}</a>
	</div>
	<ul>
		{% if status == "pending" %}
		{% for task in object_list %}{% include "iris/task_cards/station_pending.html" %}{% endfor %}
		{% elif status == "delayed" %}
		{% for task in object_list %}{% include "iris/task_cards/station_delayed.html" %}{% endfor %}
		{% elif status == "suspended" %}
		{% for task in object_list %}{% include "iris/task_cards/station_suspended.html" %}{% endfor %}
		{% elif status == "completed" %}
		{% for task in object_list %}{% include "iris/task_cards/station_completed.html" %}{% endfor %}
		{% endif %}
	</ul>
</div>
{% endblock %}